micronaut:
  application:
    name: webservices_labb_two
mongodb:
  uri: mongodb://${MONGO_USERNAME:root}:${MONGO_PASSWORD:password}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}
db:
  name: 'mydb'
  collection: 'book'
netty:
  default:
    allocator:
      max-order: 3
