name: Create and publish a Docker image

on:
  release:
    types: [ created ]

env:
  REGISTRY: ghcr.io
  ACTOR: ${{github.actor}}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package -Dpackaging=docker-native -Pgraalvm --file pom.xml

      - name: Log in to the Container registry
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set ACTOR_LC environment variable
        run: |
          echo "ACTOR_LC=${ACTOR,,}" >>${GITHUB_ENV}

      - name: Tag docker image
        run: docker image tag webservices_labb_two ghcr.io/darkendhall/webservices_labb_two:latest

      - name: Push docker image
        run: docker push ghcr.io/darkendhall/webservices_labb_two:latest
